import React,{useState} from 'react';
import {Image,KeyboardAvoidingView,Platform,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {Button,DemoNotice,Field} from '../components/UI'; import {colors} from '../constants/theme'; import type {RootStackParamList} from '../types';
const validEmail=(v:string)=>/^\S+@\S+\.\S+$/.test(v.trim());
const Shell=({children}:{children:React.ReactNode})=><KeyboardAvoidingView style={s.fill} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Image source={require('../../assets/logo-goodwe.png')} style={s.logo} accessibilityLabel="Logotipo Goodwe"/><Text style={s.tagline}>Energia para seguir o seu caminho</Text><View style={s.panel}>{children}</View></ScrollView></KeyboardAvoidingView>;
export function SignUpScreen({navigation}:NativeStackScreenProps<RootStackParamList,'SignUp'>){const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[show,setShow]=useState(false);const[error,setError]=useState('');const submit=()=>{if(!name.trim()||!password||!validEmail(email)){setError('Preencha nome, e-mail válido e senha.');return;}navigation.reset({index:0,routes:[{name:'Map'}]});};return <Shell><Text style={s.title}>Criar conta</Text><Text style={s.sub}>Crie um perfil fictício para iniciar</Text><Field label="Nome" value={name} onChangeText={setName}/><Field label="E-mail" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Field label="Senha" value={password} onChangeText={setPassword} secureTextEntry={!show}/><Button secondary title={show?'Ocultar senha':'Mostrar senha'} onPress={()=>setShow(!show)}/>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Button title="Criar conta" onPress={submit}/><Button secondary title="Já possui uma conta? Entrar" onPress={()=>navigation.navigate('Login')}/></Shell>}
export function LoginScreen({navigation}:NativeStackScreenProps<RootStackParamList,'Login'>){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[show,setShow]=useState(false);const[error,setError]=useState('');return <Shell><Text style={s.title}>Entrar</Text><DemoNotice>Login demonstrativo: qualquer e-mail válido e senha não vazia são aceitos.</DemoNotice><Field label="E-mail" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Field label="Senha" value={password} onChangeText={setPassword} secureTextEntry={!show}/><Button secondary title={show?'Ocultar senha':'Mostrar senha'} onPress={()=>setShow(!show)}/>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Button title="Entrar" onPress={()=>{if(!validEmail(email)||!password){setError('Informe um e-mail válido e uma senha.');return;}navigation.reset({index:0,routes:[{name:'Map'}]});}}/><Button secondary title="Voltar ao cadastro" onPress={()=>navigation.goBack()}/></Shell>}
const s=StyleSheet.create({fill:{flex:1,backgroundColor:colors.background},page:{flexGrow:1,justifyContent:'center',padding:22},logo:{width:210,height:105,resizeMode:'contain',alignSelf:'center'},tagline:{textAlign:'center',color:colors.muted,marginBottom:18},panel:{width:'100%',maxWidth:480,alignSelf:'center',backgroundColor:'#fff',padding:22,borderRadius:22},title:{fontSize:28,fontWeight:'900',color:colors.ink,textAlign:'center'},sub:{textAlign:'center',color:colors.muted,marginVertical:14},error:{color:colors.primary,fontWeight:'700',marginTop:6}});
